l7mp/stunner

- helm/stunner/templates/stunner-deployment.yaml
After the recent changes the "-c" switch is required.
> fix stunnerd command in helm.

- cmd/post-install/post-install.yaml
- helm/stunner/templates/post-install-job.yaml
fixing namespace issue that prevented the helm chart to be installed in namespaces other than `default`
> Fix namespace issue

- examples/kurento-magic-mirror/README.md
- examples/kurento-magic-mirror/kurento-magic-mirror-server.yaml
- examples/kurento-magic-mirror/kurento-magic-mirror-stunner.yaml
TODO: switch the link to the l7mp docker registry whenever the webrtc server
Docker image is built and pushed.
> Kurento magic mirror example with STUNner

- doc/AUTH.md
- handlers.go
- stunner_test.go
Modify the [longterm auth handler](https://github.com/l7mp/stunner/blob/4385dcf3040ae230f54498e813af9124f97598d7/handlers.go#L44) to implement the whole [server-side authentication logic](https://datatracker.ietf.org/doc/html/draft-uberti-rtcweb-turn-rest-00#section-4.2):
* split the username by the colon delimiter
* take the first item that looks like an integer (strconv.Atoi is successful)
* consider this item as a UNIX timestamp defining the expiry of the timestamp
* fail authentication if the the timestamp is in the past: timestamp < time.Now().Unix()
* otherwise take the original username, perform the HMAC and return the resultant hash
Document the changes in doc/AUTH.md and add tests.
> fix: support coturn use-auth-secret TURN auth mode, close #39

- LICENSE
- README.md
- cmd/stunnerctl/README.md
- cmd/stunnerd/README.md
- cmd/turncat/README.md
- doc/AUTH.md
- doc/CONCEPTS.md
- doc/DEPLOYMENT.md
- doc/GATEWAY.md
- doc/INSTALL.md
- doc/MONITORING.md
- doc/OBSOLETE.md
- doc/README.md
- doc/SECURITY.md
- doc/WHY.md
- examples/benchmark/README.md
- examples/cloudretro/README.md
- examples/direct-one2one-call/README.md
- examples/jitsi/README.md
- examples/kurento-magic-mirror/README.md
- examples/kurento-one2one-call/README.md
- examples/livekit/README.md
- examples/neko/README.md
- examples/simple-tunnel/README.md
As the title says, this PR bumps the year in License sections of all documents.
---
<details>
<summary>One-liner for next year:</summary>
```console
find . -type f | xargs sed -i  's/Copyright 2021-2023/Copyright 2021-2024/g'
```
</details>
> doc: Bump copyright year

- cmd/stunnerd/main.go
- go.mod
- go.sum
The [fsnotify release notes](https://github.com/fsnotify/fsnotify/releases/tag/v1.6.0) mentions a change that might fix #33:  *inotify: don't ignore events for files that don't exist (https://github.com/fsnotify/fsnotify/pull/260, https://github.com/fsnotify/fsnotify/pull/470)*.
This PR bumps fsnotify version and makes event checking more readable.
> chore: Bump fsnotify/fsnotify to v1.6.0

- .github/workflows/lint.yml
- .github/workflows/test.yml
- Dockerfile
As of the Go [release policy](https://go.dev/doc/devel/release), Go 1.18 is reaching its end of life. Accordingly, this PR bumps Go version in CI/CD pipelines and in the Dockerfile.
> chore(CI/CD): Bump Go version to 1.19

- doc/GATEWAY.md
> Fix sample Gateway YAML in docs

- .github/workflows/publish-dev.yaml
- .github/workflows/publish.yml
WIP DO NOT MERGE YET
Building the chart was moved to the l7mp/stunner-helm repository. In the new version, we use [this](https://github.com/marketplace/actions/repository-dispatch) action. It sends an event to the given repository. A PAT is used to authenticate the request.
Testing will happen by manually releasing dev versions. Dev versions are not considered stable, so they shouldn't break anyone's setup. 
Manual releasing with the `workflow_dispatch` event
> chore(CI): Propagate helm updates to l7mp/stunner-helm

- .github/workflows/publish-dev.yaml
- .github/workflows/publish.yml
- .github/workflows/test.yml
- Dockerfile
Motivated by #75, this PR adds support for building both arm64 and am64 container images with the workflows.
Note: `dev` tags already have arm64 images:
- https://hub.docker.com/r/l7mp/stunnerd/tags
- https://hub.docker.com/r/l7mp/stunner-gateway-operator/tags
> feat(CI/CD): Build arm64 container images

- config.go
Establish a test environment for stunnerd locally. Follow the steps below.
Prerequisite
- golang1.20.3
Installation
1. Download the `mediatx` from the repository [https://github.com/aler9/mediamtx.git](mediatx) as the streaming server.
- cd <your-workdir>
- git clone https://github.com/aler9/mediamtx.git
- cd mediamtx
- make binaries
- modify the config option in the `mediamtx.yml`
webrtcICEServers: [turn:user1:passwd1:<host-ip>:3478?transport=dtls]
- ./mediatx
**Note**
Replace the `host-ip` field with your own host's ip.
2. Download a binary tool called as `ffmpeg` which is used to publish a video stream to `mediatx`.
For example, on macOS, run the command like below
- brew install ffmpeg
3. Download a video material [http://vjs.zencdn.net/v/oceans.mp4](test.mp4).
- wget …
> add base64 encode for self-signed certificate and key pem data

- .github/workflows/e2e-test.yml
This PR implements a full end-to-end STUNner test:
- sets up minikube
- installs stunner/stunner-gateway-operator dev version with helm
- installs the simple-tunnel example to minikube
- builds turncat and installs iperf
- does a measurement with iperf
- if there is response from the iperf server, we assume the e2e case working
Scheduled to run at 11:00 UTC on Mondays, and can be triggered by hand as well.
> **Note**
> There is a heuristic timeout in the `Configure STUNner` step. This might be not optimal and can lead to false-positive failures.
> chore(CI): Add end-to-end test

- docs/GATEWAY.md
Updating the outdated documentation for the [pull request](https://github.com/l7mp/stunner-gateway-operator/pull/25) in the stunner-gateway-operator repository.
Issue: https://github.com/l7mp/stunner-gateway-operator/issues/21
> doc(Gateway): Mixed-protocol LB

- docs/examples/mediasoup/README.md
- docs/examples/mediasoup/mediasoup-call-stunner.yaml
- docs/examples/mediasoup/mediasoup-server.yaml
New mediasoup demo adopted from [@damhau](https://github.com/damhau)'s [repository](https://github.com/damhau/mediasoup-demo-docker). Huge thanks to them for the great demo.
PR includes: Resource manifests both for STUNner and mediasoup.
> doc: Add mediasoup demo

- docs/examples/cloudretro/README.md
- docs/examples/cloudretro/cloudretro-stunner-cleanup.yaml
- docs/examples/cloudretro/coordinator-config.sh
- docs/examples/cloudretro/stunner-gwcc.yaml
- docs/examples/cloudretro/stunner-setup-for-cloudretro.sh
Due to the fact that UDPRoutes aren't followed by their respective services anymore, but having a service for the Gateway itself, this value of the helper-script should have been changed.
> Update CloudRetro helper script

- cmd/turncat/main.go
`turncat -h` output had and extra `pflag: help requested` line. This PR removes it, and provides the extended help message text.
```
Usage of turncat:
-i, --insecure     Insecure TLS mode, accept self-signed certificates (default: false).
-l, --log string   Log level (default: all:WARN). (default "all:WARN")
-v, --verbose      Verbose logging, identical to -l all:DEBUG.
pflag: help requested
```
```
turncat [-l|--log <level>] [-i|--insecure] client server peer
client: <udp|tcp|unix>://<listener_addr>:<listener_port>
server: <turn://<auth>@<server_addr>:<server_port> | <k8s://<namesspace>/<name>:listener
peer: udp://<peer_addr>:<peer_port>
auth: <username:password|secret>
-h, --help         Display this help text and exit
-i, --insecure     Insecure TLS mode, accept self-signed …
```
> feat(turncat): Extend help message in `--help`

- .github/workflows/publish.yml
Fixes #114 
test builds are available at https://github.com/levaitamas/stunner/releases/tag/v0.17.0
discord discussion: https://discord.com/channels/945255818494902282/1075804833866596364/threads/1197474904111583242
> feat: Add `turncat` binaries as release assets

- .github/workflows/publish--add-binaries.yml
- .github/workflows/publish--push-charts.yml
- .github/workflows/publish-dev.yaml
- .github/workflows/publish.yml
- .github/workflows/test.yml
- build and release `turncat` and `stunnerctl` binaries on release
- fix node.js version warning in test action
- introduce reusable workflow for pushing helm charts (TODO: refactor docker push too)
> chore(CI/CD): Build and release stunnerctl too & more

- internal/telemetry/metrics.go
- stunner.go
Hello!
I'm currently monitoring a TURN server using Stunner (Headless deployment model) and have come across an issue with the stunner_listener_connections metric. This metric is described in the documentation as representing the "Number of active downstream connections at a listener." However, in my setup, it consistently reports a value of 16, which coincidentally matches the --udp-thread-num setting, regardless of the service's actual usage.
I found an [answer in the discord](https://discord.com/channels/945255818494902282/1173611480080449647/1173738162502258768) that explains that it is expected behavior when using UDP for Stunner as I do. And then there is an interesting message:
> That being said, we should really implement a TURN allocation counter that would wrap this API: …
> Monitoring: Allocations active metric

- docs/MONITORING.md
Hello!
This PR proposes updating the monitoring documentation to follow the changes introduced in the PR https://github.com/l7mp/stunner/pull/140, which enabled the `stunner_allocations_active` metric.
> Monitoring: Add stunner_allocations_active in the doc

- docs/examples/livekit/livekit-server.yaml
The earlier version 1.4.2 was not working as expected in Azure AKS cluster, hence upgrading the version to 1.8.0.
> Upgrading the LiveKit Server version to 1.8.0

- docs/examples/benchmark/README.md
- docs/examples/direct-one2one-call/README.md
- docs/examples/kurento-one2one-call/README.md
Small PR - mainly fixes the documentation with the `doc` -> `docs` change. It also fixes a few typos in those files.
> docs: fix broken references
